### ISSUE TITLE
Regarding the Imagenet Dataset

### ISSUE THREAD

**Issue by ChandayHunt** [YannDubs/SSL-Risk-Decomposition#1]
Dear author,
Thank you for your work. Recently when I tried to run `bash scripts/run_all.sh`, I came across an error like this: `ValueError: Imagenet data folder (imagenet256 or imagenet) not found in /data/data`. I am trying to download imagenet data but there are so many different ones [here](https://www.image-net.org/download.php). Could you please share how to download and organize data, Please? Thank you!

**Comment by YannDubs** [comment]
Hi, the ImageNet folder is the standard ImageNet 2012 Classification Dataset. I'm using the standar [torchvision loader](https://pytorch.org/vision/main/generated/torchvision.datasets.ImageNet.html#torchvision.datasets.ImageNet) so I would recommend following their steps to download the data

Note that `bash scripts/run_all.sh` is only required to reproduce results. If you want to analyze data or use the models then you don't actually need ImageNet

**Comment by YannDubs** [comment]
closing because no response, feel free to reopen if it wasn't clear!
